baseURL: https://verameanti-website.netlify.app/
languageCode: en-us
paginate: 6
theme: portio-hugo
title: Portio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    - name: Projects
      url: 'blog'
      weight: 2
  sitemap:
    - name: Home
      url: '#home'
      weight: 1
    - name: Projects
      url: 'blog'
      weight: 2
    - name: Contact
      url: 'contact'
      weight: 3
params:
  address:
    address: Regents Park, NW1 4SA London
    email: vmeanti.mam2022@london.edu
    openingHours: Working from 9am to 6pm
    phone: +44 (0)7428 749957
  blogPageURL: blog
  contactLink: contact
  copyright: All right reserved copyright © VeraMeanti 2020
  footerLogo: images/contact/vm4.png
  formspreeURL: YOUR FORMSPREE URL
  logo: images/site-navigation/vm4.png
  social:
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/verameanti/
      weight: 1
    - icon: fa-github-square
      url: https://github.com/verameanti
      weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true
