baseURL: https://verameanti-website.netlify.app/
languageCode: en-us
paginate: 6
theme: portio-hugo
title: Portio
menu:
  main:
    - name: Home
      url: '#home'
      weight: 1
    # - name: About
    #   url: '#about'
    #   weight: 2
    # - name: Service
    #   url: '#service'
    #   weight: 3
    # - name: Work
    #   url: '#portfolio'
    #   weight: 4
    # - name: Resume
    #   url: '#resume'
    #   weight: 5
    - name: Projects
      url: '#blog'
      weight: 6
    # - name: Contact
    #   url: '#contact'
    #   weight: 7
  # sitemap:
  #   - name: About me
  #     url: about
  #     weight: 1
  #   - name: Frequently Ask Question
  #     url: '#'
  #     weight: 2
  #   - name: Privacy & Policy
  #     url: '#'
  #     weight: 3
  #   - name: Latest Article
  #     url: '#'
  #     weight: 4
params:
  address:
    address: Regents Park, NW1 4SA London
    email: vmeanti.mam2022@london.edu
    openingHours: Working from 9am to 6pm
    phone: +44 (0)7428 749957
  blogPageURL: blog
  contactLink: contact
  copyright: All right reserved copyright © Portio 2020
  footerLogo: images/contact/widget-logo.png
  formspreeURL: YOUR FORMSPREE URL
  googleAnalytics: YOUR GOOGLE ANALYTICS CODE
  logo: images/site-navigation/logo.png
  map:
    APIkey: YOUR GOOGLE MAP API
    latitude: '23.7783741'
    longitude: '90.3746808'
    pinImage: images/pin.png
  social:
    # - icon: fa-facebook-official
    #   url: https://www.facebook.com/
    #   weight: 1
    - icon: fa-linkedin-square
      url: https://www.linkedin.com/in/verameanti/
      weight: 2
    # - icon: fa-pinterest-square
    #   url: https://www.pinterest.com/
    #   weight: 3
    - icon: fa-github-square
      url: https://github.com/verameanti
      weight: 4

markup:
  goldmark:
    renderer:
      unsafe: true
